### ISSUE TITLE
First organizational meeting and ideas

### ISSUE THREAD

**Issue by aleimba** [HackyHour/Goettingen#1]
Dear people interested in the HackyHour Göttingen,

this is an issue to collect ideas and organizational issues for the first HackyHour meeting in Göttingen.

Urgent issues to address are probably:
* What time (18h?) and where (SUB?) will the HackyHour take place
* At what time interval should the HackyHour take place (monthly?)
* How should the HackyHour take place, lightning talk with one specific topic at the beginning then open as help desk ...

Don't be shy and post any questions and issues in reply to this first post here!

Cheers,
Andreas

**Comment by pkra** [comment]
I'm curious if there has been a decision.

**Comment by aleimba** [comment]
Hi @pkra,

you mean a decision on the organizational issues mentioned above? The first HackyHour (7th of February from 18-19.30 pm, SUB Göttingen small seminar room) will be an organizational event to actually discuss/tackle the future HackyHour organization. You're more than welcome to join us and the discussion (http://etherpad.gwdg.de/p/GoeTeachingOpenScience).

If you want to stay up-to-date or involve our community in addition to here, you can subscribe to our mailing lists:
* We have loosely established an Open Science network here in Göttingen and everybody is welcome to join the mailing list:
    Subscribing to the general Openscience Mailinglist: https://listserv.gwdg.de/mailman/listinfo/openscience
* Additional mailing list: Göttingen Teaching Open Science
    You can subscribe to the list via https://listserv.gwdg.de/mailman/listinfo/goeteachingopenscience

Cheers,
Andreas

**Comment by pkra** [comment]
> The first HackyHour (7th of February from 18-19.30 pm, SUB Göttingen small seminar room) will be an organizational event to actually discuss/tackle the future HackyHour organization.

Thanks, I was looking for confirmation on that. Not sure I can make that but will try.

**Comment by defnull** [comment]
If you need a room: There is a hackerspace in Göttingen called "Neotopia". People there might also be interested in a group like yours. https://cccgoe.de/

**Comment by aleimba** [comment]
Hi @defnull,
the CCC hackerspace is a nice idea. @mimkes already suggested it yesterday, so it's included in our list of possible venues: http://etherpad.gwdg.de/p/HackyHourGoettingen_2017-02-07

Thanks,
Andreas
