### ISSUE TITLE
2nd Göttingen HackyHour - Jupyter notebooks

### ISSUE THREAD

**Issue by aleimba** [HackyHour/Goettingen#3]
Hello all,

we will have our 2<sup>nd</sup> Göttingen HackyHour as indicated on the website: https://hackyhour.github.io/Goettingen/

Pad: http://etherpad.gwdg.de/p/HackyHourGoettingen_2017-03-07

Our introductory topic will be Jupyter notebooks, but of course you can bring your own science-related computer programs for discussions and/or help. If you have any further ideas or questions post them here or use any of the communication channels indicated on the [website](https://hackyhour.github.io/Goettingen/#when-and-where)!

Hope to see you soon,
Andreas

**Comment by andreas-busch** [comment]
Hi Andreas,

can you clarify the "where" of the HackyHour? The etherpad says "SUB Kleiner Konferenzraum 3. OG"; the Göttingen HackyHour page (https://hackyhour.github.io/Goettingen/) states Neotopia. I'm open to both but would hate to land in the wrong place :-)

Thanks, Andreas (a common first name apparently)

**Comment by aleimba** [comment]
Hi Andreas :wink: (@anbusch),

nice spot. It's now corrected in the Etherpad.
The 2<sup>nd</sup> Göttingen HackyHour will take place on the 14<sup>th</sup> of March in the Neotopia hackspace of the Göttingen CCC (https://cccgoe.de/wiki/Neotopia), as correctly stated on our website.

Cheers,
Andreas

**Comment by andreas-busch** [comment]
Thanks!
