### ISSUE TITLE
4th Hacky Hour _ Tidy Data

### ISSUE THREAD

**Issue by njahn82** [HackyHour/Goettingen#5]
This is just to remind you about our upcoming HackyHour, which will happen next Tuesday (May 9, 6pm at the Neotopia).

The topic is Tidy Data - strategies to make data cleaning as painless as possible - introduced by [Hadley Wickham](https://github.com/hadley). He wrote a very influential paper and is maintaining many R packages around this topic. 

Here's the paper:
H. Wickham, “Tidy Data,” Journal of Statistical Software, vol. 59, no. 10, 2014. https://doi.org/10.18637/jss.v059.i10

and a link to the many R packages:
http://tidyverse.org/

During my presentation, I will briefly introduce what is actually meant by Tidy Data and present some R tools that will help you to clean up messy data. For those of you who don't have R and RStudio installed I will set up an server hosted by Amazon that will contain all dependencies, and which will be accessible via a web browser. I'll share the link with you when we meet.

See you,

Najko

**Comment by njahn82** [comment]
Thanks for coming and apologies for not being able to add you as users to the web-based RStudio server.

Here are the slides:
https://hackyhour.github.io/Goettingen/slides/tidy_slides.html

**Comment by aleimba** [comment]
@njahn82 no worries about the server. It's also good if people install stuff during the HH, at least I could figure out how to install the whole tidyverse!

Thanks for the slides. This is a markdown file and you can convert it in Rstudio to html?!

**Comment by njahn82** [comment]
Apologies. I added the `.Rpres` file, which is the source file of my presentation. These files can be rendered in RStudio. Here's a useful introduction:
<https://support.rstudio.com/hc/en-us/articles/200486468-Authoring-R-Presentations>
